### ISSUE TITLE
servant-client-ghcjs

### ISSUE THREAD

**Issue by rikvdkleij** [FPtje/miso-isomorphic-example#17] opened 2019-06-28 12:33 UTC
I want to add `servant-client-ghcjs` to this project but I do not know how because this package is not available in nix, Also because the Haskell nix tutorials have a different setup in which Haskell packages are defined with `mkDerivation` (by using `cabal2nix`).

Can you help me?

**Comment by FPtje** [comment] 2019-06-28 17:53
In the let binding of `nixpkgs.nix`, add the following definitions:

```nix
Edit: See post below
```

Then, in the list of ghcjs overrides (along with servant-client, servant and quite a few others), add the following:

```nix
servant-client-ghcjs = servant-package "servant-client-ghcjs";
```

Note: In reality you'll probably want all servant related packages to have the exact same version, so instead of *just* adding `servant-client-ghcjs`, you should define all the servant packages you use in the same way:
```nix
servant = dontCheck (servant-package "servant"); # dontCheck because in our systems the tests fail
servant-client = dontCheck (servant-package "servant-client");
servant-client-core = servant-package "servant-client-core";
servant-client-ghcjs = servant-package "servant-client-ghcjs";
```

See the top level directories in https://github.com/haskell-servant/servant to find out which servant libraries can be packaged like that.

I'll close this issue for now. Follow-up questions can be asked in this issue, even when closed.

**Comment by rikvdkleij** [comment] 2019-06-28 18:10
Thanks!

Where do I have to put
```
# Function to quickly define a servant package
servant-package = name :
    doJailbreak (super.callCabal2nix name (servant-src + "/${name}") {});
```
?

Nix complains that it does not know `doJailbreak`. I have tried some different solutions but none of them is working.

**Comment by rikvdkleij** [comment] 2019-06-28 18:11
Btw, I have changed 
```
servant-src = previous.fetchFromGitHub {
```
to
```
servant-src = bootstrap.fetchFromGitHub {
```

**Comment by FPtje** [comment] 2019-06-28 18:18
You're right, the code above doesn't work. I should have tested it before posting.

I'll just post the whole `nixpkgs.nix`. The following compiles on my system:

```nix
let
  bootstrap = import <nixpkgs> {};

  nixpkgs-src = bootstrap.fetchFromGitHub {
    owner = "NixOS";
    repo  = "nixpkgs";
    rev = "725b5499b89fe80d7cfbb00bd3c140a73cbdd97f";
    sha256 = "0xdhv9k0nq8d91qdw66d6ln2jsqc9ij7r24l9jnv4c4bfpl4ayy7";
  };

  servant-src = bootstrap.fetchFromGitHub {
    owner = "haskell-servant";
    repo = "servant";
    # Note: Decide which revision to use!
    rev = "e3e5d2b23057c2c3409e5e210b613527baf3b77d";
    # The correct sha256 is shown in the error when you change the revision
    sha256 = "0n9xn2f61mprnvn9838zbl4dv2ynnl0kxxrcpf5c0igdrks8pqws";
  };

  config = {
    packageOverrides = pkgs: rec {
      haskell = pkgs.haskell // {
        packages = pkgs.haskell.packages // {

          ghc = pkgs.haskell.packages.ghc864;

          } // {

          # Many packages don't build on ghcjs because of a dependency on doctest
          # (which doesn't build), or because of a runtime error during the test run.
          # See: https://github.com/ghcjs/ghcjs/issues/711
          ghcjs = pkgs.haskell.packages.ghcjs86.override {
            overrides = self: super: with pkgs.haskell.lib; let
              servant-package = name :
                pkgs.haskell.lib.doJailbreak (super.callCabal2nix name (servant-src + "/${name}") {});
              in {
                tasty-quickcheck = dontCheck super.tasty-quickcheck;
                http-types       = dontCheck super.http-types;
                http-media       = dontCheck super.http-media;
                comonad          = dontCheck super.comonad;
                semigroupoids    = dontCheck super.semigroupoids;
                lens             = dontCheck super.lens;
                QuickCheck       = dontCheck super.QuickCheck;

                network = dontCheck (doJailbreak super.network_2_6_3_1);
                servant = dontCheck (servant-package "servant"); # dontCheck because in our systems the tests fail
                servant-client = dontCheck (servant-package "servant-client");
                servant-client-core = servant-package "servant-client-core";
                servant-client-ghcjs = servant-package "servant-client-ghcjs";
              };
          };
        };
      };
    };
  };

in
  import nixpkgs-src { inherit config; }
```

**Comment by rikvdkleij** [comment] 2019-06-28 20:08
Thanks again!

Next issue:
```
ghc: can't find a package database at /home/rik/.cabal/store/ghc-8.6.4/package.db
```
Weird that nix tries to find my local package.db

**Comment by FPtje** [comment] 2019-06-28 20:14
That is indeed odd. I haven't seen that issue before. I'll look into it tomorrow.

**Comment by rikvdkleij** [comment] 2019-06-29 10:30
It would be really cool to make this example project just working in way that it only necessary to use nix to install the ghcjs compiler:
```
nix-env -iA nixpkgs.haskell.compiler.ghcjs
```
Together with a cabal new-* style project which contains cabal.project file. That would made the project setup much more simple or at least understandable (for me).

In that way I  can also use my IntelliJ-Haskell plugin :smile:

**Comment by FPtje** [comment] 2019-06-29 12:32
I would expect nix to be able to do everything on its own. I would strongly recommend *against* installing ghcjs in your user's `nix-env` environment. This causes ghcjs binaries and libraries to present in every shell you open. In this project, the `nixpkgs.nix` file provides the right version of ghc and ghcjs. I can imagine that if you open a shell, that cabal build might use your nix-env ghcjs instead of the one defined by the nix files.

To build this project, I'd recommend `cd`'ing into the directory and running `nix-build` or `nix build`. To open an interactive shell where ghcjs and everything is available (and you can run cabal build), run `nix-shell` in the directory.

If that doesn't work, try removing all Haskell related packages from your `nix-env`. 

> In that way I can also use my IntelliJ-Haskell plugin 

Editor plugins and nix often need a little nudge to cooperate. The nix ideal is that you never have dependencies, compilers and whatnot installed globally, instead having them available in shells for specific projects. This allows you to work on multiple projects with different versions of basically everything without conflicts ever being a problem. Editors, however, generally expect to find such tools in the global path. There are two ways to solve this: get your editor to be in an environment (e.g. nix-shell) where those tools are available, OR, preferably, Make your tool use the project's `shell.nix` or `default.nix` file. The latter is what I do for a simple custom ghc linter in Sublime.

**Comment by rikvdkleij** [comment] 2019-06-29 12:45
Ok, clear!

I will find a solution to get this working in the IntelliJ Haskell plugin with nix-shell.

Can you reproduce my issue about searching for a package db?

**Comment by FPtje** [comment] 2019-06-29 14:09
Sadly, no. When I open a nix shell or try to `nix build` it works just fine. Have you tried removing ghc and ghcjs from your `nix-env`?

**Comment by rikvdkleij** [comment] 2019-06-29 14:53
I did not install ghc or ghcjs via `nix-env`:
```
$nix-env -q
cabal2nix-2.13
nix-2.2.2
nix-bash-completions-0.6.6
```

**Comment by rikvdkleij** [comment] 2019-06-29 14:56
I had installed GHC 8.6.5 by ghcup but I have removed everything from PATH.

**Comment by rikvdkleij** [comment] 2019-06-29 15:02
Ok, I found the issue.

Yesterday I did `cabal new-build` in `nix-shell` which had created
```
common/.ghc.environment.x86_64-linux-8.6.4
```
After removing that file the `nix build` is working.

Sorry for that.

Btw, is it possible to use GHC 8.6.5?

**Comment by rikvdkleij** [comment] 2019-06-29 15:14
On a second thought, that's a really a pity that `cabal new-build` conflicts with the `nix-build` in the context of development.

Edited: Ok, so that will mean I can only use the legacy style Cabal build.

**Comment by FPtje** [comment] 2019-06-29 15:20
I haven't really looked into the v2 side of Cabal. I only know that it was inspired by nix and has very similar features.

> Btw, is it possible to use GHC 8.6.5?

Possibly, if it has been packaged upstream in nixpkgs.

I'll close the issue again, as it seems to have been answered.

**Comment by rikvdkleij** [comment] 2019-06-29 15:21
Thanks for helping!!

**Closed as completed by FPtje** 2019-06-29 15:20 UTC

**Comment by rikvdkleij** [comment] 2019-06-29 15:27
FYI, this prevent the generation ghc environment files;
```
cabal new-build --write-ghc-environment-files=never
```

**Comment by rikvdkleij** [comment] 2019-06-29 19:40
Yet another question. Hopefully you still want to help me...

How did you know that you had to use revision
```
e3e5d2b23057c2c3409e5e210b613527baf3b77d
```
for servant? It seems to be the only version that is working.

I upgrade the revision to 0.16.1 but run from one problem to another....  I do not get it working. 

Before I changed the `nixpkgs.nix` completely the error was:
```
hash mismatch in fixed-output derivation '/nix/store/x8026ghqf9hascprnm0iq8g9p3wlggrr-servant-client-core-0.16-r1.cabal':
  wanted: sha256:1sps3bwx963lm1788m859pwbxmaiqpiiv21rygfnigzkanc5czj4
  got:    sha256:1hanl8sz14z11441ng8vkzpxrl6igk3xzp6fcm6wg59fsb30fh29
```

**Comment by rikvdkleij** [comment] 2019-06-29 19:44
Another question. Why did you not override the servant packages in `ghc` and only in `ghcjs`?

**Comment by FPtje** [comment] 2019-06-29 19:47
Most revisions should work, be it that tests sometimes need to be disabled. The sha error means you should update the sha in the nix file. See the comment above one of the sha256 lines.

I didn't override the servant packages in ghc probably because they compiled just give while the ghcjs versions didn't. This might at some point cause incompatibilities.

**Comment by rikvdkleij** [comment] 2019-06-29 19:57
>  The sha error means you should update the sha in the nix file. See the comment above one of the sha256 lines.

Yes, it looks like that but I think it is a different issue because I have set the revision of `haskell-servant/servant`, not for `servant-client-core`

**Comment by FPtje** [comment] 2019-06-30 07:46
Here are my steps as I update the servant revision in `nixpkgs.nix`. They include thinking steps:

- Updated `rev` field of servant-src to latest master
- Run `nix-build`, find out that the servant packages aren't being rebuilt. From earlier experience, I know that `fetchFromGithub` uses [fixed output paths](http://lethalman.blogspot.com/2015/01/nix-pill-18-nix-store-paths.html) (scroll down to `Fixed-output paths`), meaning sadly that it won't know a derivation has changed unless the `sha256` field is modified.
- Change one letter of the `sha256` field, to help nix figure out that the version has changed
- Run a `nix-build` I know will fail, to get the correct sha256 from the error message, and fill it in (alternative for these three steps is using a command called `nix-prefetch-git`)
- Added dummy `servant-client-ghcjs` to the client's cabal file build dependencies, to make sure it's being built. In your case you're genuinely using it, so it should be built anyway.
- Run proper `nix-build`. Note: I choose `nix-build` here over `nix build` because the former shows full build output. When errors occur `nix build` only shows the last 10 lines, `nix-build` shows the entire log. Alternatively you can run `nix build` and then run `nix log <failed package drv>` to see the build output.

I end up with the following `nixpkgs.nix` file:

```nix
let

  bootstrap = import <nixpkgs> {};

  nixpkgs-src = bootstrap.fetchFromGitHub {
    owner = "NixOS";
    repo  = "nixpkgs";
    rev = "725b5499b89fe80d7cfbb00bd3c140a73cbdd97f";
    sha256 = "0xdhv9k0nq8d91qdw66d6ln2jsqc9ij7r24l9jnv4c4bfpl4ayy7";
  };

  servant-src = bootstrap.fetchFromGitHub {
    owner = "haskell-servant";
    repo = "servant";
    # Note: Decide which revision to use!
    rev = "0f590dc7d92045caec52fa03aa473ebfaac1c908";
    # The correct sha256 is shown in the error when you change the revision
    sha256 = "0pp1k0qwjj04ks93lcz9py9ajxb3m8nbp4m3v3hyc9xmn93p35ma";
  };

  config = {
    packageOverrides = pkgs: rec {
      haskell = pkgs.haskell // {
        packages = pkgs.haskell.packages // {

          ghc = pkgs.haskell.packages.ghc864;

          } // {

          # Many packages don't build on ghcjs because of a dependency on doctest
          # (which doesn't build), or because of a runtime error during the test run.
          # See: https://github.com/ghcjs/ghcjs/issues/711
          ghcjs = pkgs.haskell.packages.ghcjs86.override {
            overrides = self: super: with pkgs.haskell.lib; let
              servant-package = name :
                pkgs.haskell.lib.doJailbreak (super.callCabal2nix name (servant-src + "/${name}") {});
              in {
                tasty-quickcheck = dontCheck super.tasty-quickcheck;
                http-types       = dontCheck super.http-types;
                http-media       = dontCheck super.http-media;
                comonad          = dontCheck super.comonad;
                semigroupoids    = dontCheck super.semigroupoids;
                lens             = dontCheck super.lens;
                QuickCheck       = dontCheck super.QuickCheck;

                network = dontCheck (doJailbreak super.network_2_6_3_1);
                servant = dontCheck (servant-package "servant"); # dontCheck because in our systems the tests fail
                servant-client = dontCheck (servant-package "servant-client");
                servant-client-core = servant-package "servant-client-core";
                servant-client-ghcjs = servant-package "servant-client-ghcjs";
              };
          };
        };
      };
    };
  };

in
  import nixpkgs-src { inherit config; }
```

Interestingly I didn't hit your sha256 problem. I think this might be because I realised nix wasn't rebuilding the derivations early. I think you might hit the error when some servant packages have been built, but others have not.

Hypothetically, I could have started hitting problems like:
- Errors about not having the right versions of packages. This is particularly prevalent with `servant`, as they put version bounds on their libraries that are quite a bit more strict than strictly necessary.
- Tests failing or taking forever (there's a bug in ghcjs [reported here](https://github.com/ghcjs/ghcjs/issues/711))
- Type errors when building servant

Solutions to the first and second problem are `doJailbreak` (wipes version bounds) and `dontCheck` (don't run tests) respectively. You can see the `nixpkgs.nix` file already contains a couple of these. That's because I've hit those problems in the past.

The third problem could be caused by `doJailBreak` as it would turn out that the version of a dependency you have *really* doesn't work. A solution then is to package a version of the dependency that *does* work. In other cases I've had type errors in libraries because of a ghc upgrade. In that case the solution is updating the package to a version that *does* support your version of ghc. In the worst case you might have to fork the package, fix it, create a PR and package your fork until your PR has been merged and released. If the package turns out to be abandonware, look for alternatives.

**Comment by rikvdkleij** [comment] 2019-06-30 13:39
Amazing this is just works for you!

Thanks for your elaborate explanation!

I used the revision of the 0.16.1 tag instead of master but that should not matter.

I also hit a dependency issue with `servant-lucid`. The build was using 0.8 version which not allows servant 0.16. So I assumed that the revision of `nixpkgs` was fixed to 0.8 version. 
(Can you tell me how I can see which package versions are in a certain `nixpkgs` revision?)

So I thought, I also have to `fetchFromGitHub` the `servant-lucid` version 0.9 which allows servant 0.16. And so on..
But for you it just works. I'm confused. The `nixpkgs` revision of your script is the same as before.

**Comment by FPtje** [comment] 2019-06-30 14:03
Run `nix repl nixpkgs.nix` to open a repl. In there you can type `haskellPackages.servant-lucid` to find it's on 0.8.1.

Also, the server part of the isomorphic example already uses `servant-lucid`, and it compiles with `nix-build`. So for the version of servant I posted above, `servant-lucid` works.

> The build was using 0.8 version which not allows servant 0.16.

Does the `doJailbreak` I mentioned above not fix this?

Honestly copy pasting the above `nixpkgs.nix` should make `nix-build` work no matter what. That's the whole point of reproducible builds. It works for me, nix has reproducible builds, so it must work for you. There's no state on my machine that should be affecting nix-build here. If it doesn't work, please tell me the precise commands you enter in the terminal, and give the exact error messages.

**Comment by rikvdkleij** [comment] 2019-06-30 19:31
Your script works. The only difference in comparison with my script is that I was using the revision of the 0.16.1 tag. I also first changed the revision, then build to see the correct sha and then build again. Weird.

> Does the doJailbreak I mentioned above not fix this?

The jailbreak is only for `servant` packages, not for `servant-lucid`. But your script works.

> That's the whole point of reproducible builds

I already noticed before that there is some "hidden" state in nix. Some time ago I found out (for another project did that not build) that it was working after a `nix-collect-garbage`...

>  A solution then is to package a version of the dependency that does work. 

What do mean by that?

And thanks again for help!! Nix is still a bit incomprehensible to me.

**Comment by rikvdkleij** [comment] 2019-06-30 19:36
Hmm, did not check everything yet.

The build contains servant 0.15?
And I expected `servant-lucid` 0.9

```
nix-repl> haskellPackages.servant-lucid
«derivation /nix/store/2f3w9vsp67arw7k9gmifimrwpfpric06-servant-lucid-0.8.1.drv»

nix-repl> haskellPackages.servant      
«derivation /nix/store/jr0c53avb3dvp4cydf5f6dj5lcgnlbxn-servant-0.15.drv»

nix-repl> haskellPackages.servant-client
«derivation /nix/store/mwn95b9krdh9w2h4c2zchrix4p6lfwga-servant-client-0.15.drv»

nix-repl> haskellPackages.servant-server
«derivation /nix/store/k1dp5a61wp98shwdr28pj05fjzg00bz0-servant-server-0.15.drv»

```

**Comment by rikvdkleij** [comment] 2019-06-30 19:51
So back again to revision of tag 0.16.1
After setting sha correctly:
```
these derivations will be built:
  /nix/store/val6frhchihs6rwsv8pl5fbzp3l4mzkm-servant-client-core-0.16-r1.cabal.drv
  /nix/store/43sbz5whnrsrrb8378wrdg87ngrqx78w-servant-client-core-0.16.drv
  /nix/store/fkgq9hqi3lx0nyh2i1lwan9qr42b6j1a-servant-client-ghcjs-0.16.drv
  /nix/store/d4kjxk5h61syvx1r4sg6a157l3j1j9ji-client-0.1.0.0.drv
  /nix/store/4cd9dh56mhylp9qkv3nsrymp8sp8h4jy-client.drv
  /nix/store/jcadvbnax1xq8rfarx3v1ng33pf78fcd-miso-ismorphic-example.drv
building '/nix/store/val6frhchihs6rwsv8pl5fbzp3l4mzkm-servant-client-core-0.16-r1.cabal.drv'...

trying http://hackage.haskell.org/package/servant-client-core-0.16/revision/1.cabal
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3531    0  3531    0     0   3772      0 --:--:-- --:--:-- --:--:--  3772
hash mismatch in fixed-output derivation '/nix/store/x8026ghqf9hascprnm0iq8g9p3wlggrr-servant-client-core-0.16-r1.cabal':
  wanted: sha256:1sps3bwx963lm1788m859pwbxmaiqpiiv21rygfnigzkanc5czj4
  got:    sha256:1hanl8sz14z11441ng8vkzpxrl6igk3xzp6fcm6wg59fsb30fh29
cannot build derivation '/nix/store/43sbz5whnrsrrb8378wrdg87ngrqx78w-servant-client-core-0.16.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/fkgq9hqi3lx0nyh2i1lwan9qr42b6j1a-servant-client-ghcjs-0.16.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/d4kjxk5h61syvx1r4sg6a157l3j1j9ji-client-0.1.0.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/4cd9dh56mhylp9qkv3nsrymp8sp8h4jy-client.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/jcadvbnax1xq8rfarx3v1ng33pf78fcd-miso-ismorphic-example.drv': 1 dependencies couldn't be built
error: build of '/nix/store/jcadvbnax1xq8rfarx3v1ng33pf78fcd-miso-ismorphic-example.drv' failed
```

Then I comment out:
```
 #               servant-client-core = servant-package "servant-client-core";
```
because this dependency is not directly needed.

Build again:
```
these derivations will be built:
  /nix/store/whh8rklsszmq01zny1fxlazmyzdb9g52-servant-client-core-0.15.drv
  /nix/store/hhjz15c1d6cl4r07nzmr4xj9mpbws3cx-servant-client-ghcjs-0.16.drv
  /nix/store/6f2kxl2c5sgvl70ma8pc8nn1mkri28is-client-0.1.0.0.drv
  /nix/store/qxpqi1ad0m0r17wjaih32nbaxhd9n3a4-client.drv
  /nix/store/mqwj9wjbmkxsrwimk5qyflkd0mq7w6gh-miso-ismorphic-example.drv
building '/nix/store/whh8rklsszmq01zny1fxlazmyzdb9g52-servant-client-core-0.15.drv'...
setupCompilerEnvironmentPhase
Build with /nix/store/k1xrzlfsx38y3mnpsia5sr479yjqymqd-ghcjs-8.6.0.1.
unpacking sources
unpacking source archive /nix/store/1lsrvmb07w0gp794jqs55vs270v62g7l-servant-client-core-0.15.tar.gz
source root is servant-client-core-0.15
setting SOURCE_DATE_EPOCH to timestamp 1000000000 of file servant-client-core-0.15/test/Spec.hs
patching sources
applying patch /nix/store/9p5ps7vk03y8hkplaj3xfx1spksfijmr-servant-client-core-streamBody.patch
patching file src/Servant/Client/Core/Internal/HasClient.hs
Hunk #4 succeeded at 550 with fuzz 2.
compileBuildDriverPhase
setupCompileFlags: -package-db=/build/setup-package.conf.d -j4 -threaded
[1 of 1] Compiling Main             ( Setup.hs, /build/Main.o )
Linking Setup ...
configuring
configureFlags: --verbose --prefix=/nix/store/pny57kgkj00i8wjm2d7d78cr48j2g12h-servant-client-core-0.15 --libdir=$prefix/lib/$compiler --libsubdir=$abi/$libname --docdir=/nix/store/6c8yjdyfrmpzyfp7npbxbxwln3flg4zc-servant-client-core-0.15-doc/share/doc/servant-client-core-0.15 --with-gcc=gcc --package-db=/build/package.conf.d --ghc-option=-j4 --disable-split-objs --enable-library-profiling --profiling-detail=exported-functions --disable-profiling --enable-shared --disable-coverage --enable-static --disable-executable-dynamic --enable-tests --disable-benchmarks --enable-library-vanilla --enable-library-for-ghci --ghc-option=-split-sections --disable-library-stripping --disable-executable-stripping --ghcjs
Using Parsec parser
Configuring servant-client-core-0.15...
CallStack (from HasCallStack):
  die', called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:950:20 in Cabal-2.4.0.1:Distribution.Simple.Configure
  configureFinalizedPackage, called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:460:12 in Cabal-2.4.0.1:Distribution.Simple.Configure
  configure, called at libraries/Cabal/Cabal/Distribution/Simple.hs:596:20 in Cabal-2.4.0.1:Distribution.Simple
  confHook, called at libraries/Cabal/Cabal/Distribution/Simple/UserHooks.hs:67:5 in Cabal-2.4.0.1:Distribution.Simple.UserHooks
  configureAction, called at libraries/Cabal/Cabal/Distribution/Simple.hs:178:19 in Cabal-2.4.0.1:Distribution.Simple
  defaultMainHelper, called at libraries/Cabal/Cabal/Distribution/Simple.hs:115:27 in Cabal-2.4.0.1:Distribution.Simple
  defaultMain, called at Setup.hs:2:8 in main:Main
Setup: Encountered missing dependencies:
servant ==0.15.*

builder for '/nix/store/whh8rklsszmq01zny1fxlazmyzdb9g52-servant-client-core-0.15.drv' failed with exit code 1
cannot build derivation '/nix/store/hhjz15c1d6cl4r07nzmr4xj9mpbws3cx-servant-client-ghcjs-0.16.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/6f2kxl2c5sgvl70ma8pc8nn1mkri28is-client-0.1.0.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/qxpqi1ad0m0r17wjaih32nbaxhd9n3a4-client.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/mqwj9wjbmkxsrwimk5qyflkd0mq7w6gh-miso-ismorphic-example.drv': 1 dependencies couldn't be built
error: build of '/nix/store/mqwj9wjbmkxsrwimk5qyflkd0mq7w6gh-miso-ismorphic-example.drv' failed

```

**Comment by FPtje** [comment] 2019-06-30 19:56
Servant-client-core is needed for servant-client-ghcjs. As you can see in the error, where it's trying to build an outdated version of it.

**Comment by rikvdkleij** [comment] 2019-06-30 20:03
> Servant-client-core is needed for servant-client-ghcjs. As you can see in the error, where it's trying to build an outdated version of it.

Ok, I see, but is should not matter when `servant-client-ghcjs` depends on `servant-client-core`.
So it's more trying to find right build path, in the context of the jail break, so nix can complete the build.

**Comment by rikvdkleij** [comment] 2019-06-30 20:05
Back to the case with `servant-client-core` enabled.

```
 /nix/store/val6frhchihs6rwsv8pl5fbzp3l4mzkm-servant-client-core-0.16-r1.cabal.drv
  /nix/store/43sbz5whnrsrrb8378wrdg87ngrqx78w-servant-client-core-0.16.drv
```

Where does the `r1` comes from? I have seen that also yesterday.

**Comment by FPtje** [comment] 2019-06-30 20:05
There is no trying to find paths in contexts of jailbreaks. The older, non-overridden version of servant-client-core requires servant==0.15.*, which the version in your nixpkgs.nix is not. Uncomment the override in nixpkgs.nix and a newer version of servant-client-core will require the right version of servant.

**Comment by rikvdkleij** [comment] 2019-07-01 18:57
Do you understand why the revision of master works and the revision of tag 0.16.1 or branch 0.16 not?

Btw, the build of your script only builds the `client` with servant 0.16. The `server` and `common` are built with servant 0.15. So that will mean that also for `ghc` the servant packages should be overridden.

**Comment by FPtje** [comment] 2019-07-02 17:28
I don't get any build errors when setting the servant revision to `e0d3f7850e63bea4214d29b0d616efe69841b083`, which is the revision of `0.16.1` as of now.

> So that will mean that also for ghc the servant packages should be overridden.

Yes. All overrides in `nixpkgs.nix` currently only override ghcjs packages. Ghc packages can be overridden in a similar way. Change this line:

```nix
ghc = pkgs.haskell.packages.ghc864;

```

To look like the ghcjs thing a couple lines down.

**Comment by rikvdkleij** [comment] 2019-07-02 19:32
Weird, when I use your script and only replace rev and sha256:
```
these derivations will be built:
  /nix/store/val6frhchihs6rwsv8pl5fbzp3l4mzkm-servant-client-core-0.16-r1.cabal.drv
  /nix/store/43sbz5whnrsrrb8378wrdg87ngrqx78w-servant-client-core-0.16.drv
  /nix/store/fkgq9hqi3lx0nyh2i1lwan9qr42b6j1a-servant-client-ghcjs-0.16.drv
  /nix/store/d4kjxk5h61syvx1r4sg6a157l3j1j9ji-client-0.1.0.0.drv
  /nix/store/4cd9dh56mhylp9qkv3nsrymp8sp8h4jy-client.drv
  /nix/store/dfklqnma8f3h2zxqzi9br3zjxczw7mh5-miso-ismorphic-example.drv
building '/nix/store/val6frhchihs6rwsv8pl5fbzp3l4mzkm-servant-client-core-0.16-r1.cabal.drv'...

trying http://hackage.haskell.org/package/servant-client-core-0.16/revision/1.cabal
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3531    0  3531    0     0  10117      0 --:--:-- --:--:-- --:--:-- 10117
hash mismatch in fixed-output derivation '/nix/store/x8026ghqf9hascprnm0iq8g9p3wlggrr-servant-client-core-0.16-r1.cabal':
  wanted: sha256:1sps3bwx963lm1788m859pwbxmaiqpiiv21rygfnigzkanc5czj4
  got:    sha256:1hanl8sz14z11441ng8vkzpxrl6igk3xzp6fcm6wg59fsb30fh29
cannot build derivation '/nix/store/43sbz5whnrsrrb8378wrdg87ngrqx78w-servant-client-core-0.16.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/fkgq9hqi3lx0nyh2i1lwan9qr42b6j1a-servant-client-ghcjs-0.16.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/d4kjxk5h61syvx1r4sg6a157l3j1j9ji-client-0.1.0.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/4cd9dh56mhylp9qkv3nsrymp8sp8h4jy-client.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/dfklqnma8f3h2zxqzi9br3zjxczw7mh5-miso-ismorphic-example.drv': 1 dependencies couldn't be built
error: build of '/nix/store/dfklqnma8f3h2zxqzi9br3zjxczw7mh5-miso-ismorphic-example.drv' failed
```

So, maybe I have cleanup again with `nix-collect-garbage`


> To look like the ghcjs thing a couple lines down.

That build fails because `servant-lucid` 0.8 depends on servant 0.15. Would you solve that also with `fetchFromGithub` and an "override" or it possible to refer to version 0.9 (which is in `nixpkgs`)?

**Comment by rikvdkleij** [comment] 2019-07-03 18:32
I hit this problem every time:
```
nix-store --verify --check-contents --repair
reading the Nix store...
checking path existence...
path '/nix/store/val6frhchihs6rwsv8pl5fbzp3l4mzkm-servant-client-core-0.16-r1.cabal.drv' disappeared, but it still has valid referrers!
warning: cannot repair path '/nix/store/val6frhchihs6rwsv8pl5fbzp3l4mzkm-servant-client-core-0.16-r1.cabal.drv'
checking hashes...
warning: not all errors were fixed
```

**Comment by rikvdkleij** [comment] 2019-07-03 19:08
Even after a complete reinstall of nix I got the same build error but
`nix-store --verify --check-contents --repair` does not give errors anymore.

**Comment by FPtje** [comment] 2019-07-03 20:59
It looks like something broke that path in the nix store. Using s different version of servant will probably solve that problem, as it will generate a new drv for servant-client-core.

**Comment by rikvdkleij** [comment] 2019-07-04 19:44
> It looks like something broke that path in the nix store. Using s different version of servant will probably solve that problem, as it will generate a new drv for servant-client-core.

Version 0.16 works.
