### ISSUE TITLE
Add `Capture` to one of the routes

### ISSUE THREAD

**Issue by tysonzero** [FPtje/miso-isomorphic-example#7] opened 2018-03-17 22:43 UTC
Having a route that captures values would be nice to have in the example.

**Comment by FPtje** [comment] 2018-03-17 23:29
I appreciate your ideas, though I'd like to keep the examples as simple as possible. Adding a third route would make the example more complex, which is a high price for an example that aims to be minimal.

It could be worth the price if there's a really good reason. Have you hit significant hurdles getting it to work?

**Comment by tysonzero** [comment] 2018-03-18 00:32
@FPtje Yeah I have hit some substantial hurdles. I was getting some extremely uninformative error messages about `undefined` not having a `length` property. After some debugging it seems that the server succeeds in parsing the URL, but the client does not for some reason, leading to a runtime crash when using the `miso` function.

The front end code is as follows, and I'm not sure why it doesn't work:

```
mainView :: AppState -> View AppAction
mainView m = case runRoute (Proxy @Routes) viewTree m of
    Left _ -> text "404 Not Found"
    Right v -> v
  where
    viewTree = homeView :<|> fooView

type Routes = HomeRoute
         :<|> FooRoute

type HomeRoute = View AppAction
type FooRoute = "foo" :> Capture "id" Int :> View AppAction

homeView :: s -> View a
homeView _ _ = div_ [] []

fooView :: Int -> s -> View a
fooView _ _ = div_ [] []
```

**Comment by FPtje** [comment] 2018-03-18 11:39
I couldn't reproduce your issue. I tried with the following patch applied to df8cb057d65eab68df58fe7c23da687b787ac5f1:

```diff
diff --git a/server/Main.hs b/server/Main.hs
index 41d3552..e97ef58 100644
--- a/server/Main.hs
+++ b/server/Main.hs
@@ -56,8 +56,8 @@ app =
     -- Alternative type:
     -- Servant.Server (ToServerRoutes Common.Flipped HtmlPage Common.Action)
     -- Renders the /flipped page.
-    flippedServer :: Servant.Handler (HtmlPage (View Common.Action))
-    flippedServer =
+    flippedServer :: Int -> Servant.Handler (HtmlPage (View Common.Action))
+    flippedServer _ =
         pure $ HtmlPage $
           Common.viewModel $
           Common.initialModel Common.flippedLink
diff --git a/shared/Common.hs b/shared/Common.hs
index 449b0d0..0466a6f 100644
--- a/shared/Common.hs
+++ b/shared/Common.hs
@@ -10,7 +10,7 @@ module Common where
 import Control.Lens
 import Data.Proxy ( Proxy(..) )
 import qualified Servant.API as Servant
-import Servant.API ( (:<|>)(..), (:>) )
+import Servant.API ( (:<|>)(..), (:>), Capture )
 #if MIN_VERSION_servant(0,10,0)
 import qualified Servant.Utils.Links as Servant
 #endif
@@ -50,7 +50,7 @@ type ViewRoutes = Home :<|> Flipped
 type Home = View Action
 
 -- Flipped route, same as Home, but with the buttons flipped
-type Flipped = "flipped" :> View Action
+type Flipped = "flipped" :> Capture "id" Int :> View Action
 
 makeLenses ''Model
 
@@ -65,7 +65,7 @@ viewModel m =
 -- Should follow the structure of ViewRoutes
 viewTree
     ::      (Model -> View Action)
-       :<|> (Model -> View Action)
+       :<|> (Int -> Model -> View Action)
 viewTree = homeView :<|> flippedView
 
 -- View function of the Home route
@@ -82,8 +82,8 @@ homeView m =
       ]
 
 -- View function of the Home route
-flippedView :: Model -> View Action
-flippedView m =
+flippedView :: Int -> Model -> View Action
+flippedView _i m =
     div_ []
       [ div_
         []
@@ -111,7 +111,7 @@ homeLink =
 flippedLink :: Network.URI
 flippedLink =
 #if MIN_VERSION_servant(0,10,0)
-    Servant.linkURI $ Servant.safeLink (Proxy @ViewRoutes) (Proxy @Flipped)
+    Servant.linkURI $ Servant.safeLink (Proxy @ViewRoutes) (Proxy @Flipped) 0
 #else
     safeLink (Proxy @ViewRoutes) (Proxy @Flipped)
 #endif
```

I did find an error where it wouldn't find `all.js` when navigating to or refreshing the flipped route. That's fixed in f0d36d21c3795c9652b6608b361257649e06e913

**Comment by tysonzero** [comment] 2018-03-18 18:13
I figured out the issue. The server/servant treats trailing slashes as optional, but the client/`runRoute` treats trailing slashes as invalid. If I go to `/foo/1` instead of `/foo/1/` everything works fine, still probably needs adjustment somewhere as this is not a fun issue to debug.

**Comment by FPtje** [comment] 2018-03-18 22:17
Again, I cannot reproduce it, perhaps because of f0d36d21c3795c9652b6608b361257649e06e913. Are you using a different version of Miso? If you are, you might have hit a bug.

In the meantime I think I can close the issue. With f0d36d21c3795c9652b6608b361257649e06e913, making a route with a `Capture` *shouldn't* be a problem. In the meantime we can continue figuring out what's going on in this issue.

**Closed as completed by FPtje** 2018-03-18 22:17 UTC
